### ISSUE TITLE
[ISSUE] Cards and the text under them look to close

### ISSUE THREAD

**Issue by Saswat7101** [hackclubiter/workshops#1]
Any text below the cards of workshops appear too close and the text styling looks too bland.

![image](https://user-images.githubusercontent.com/53933493/132131458-eef58a6e-f551-41b2-bfab-f0f0b78673d6.png)

I would suggest some space between them and also put them into a box or something like that so that the number gets noticed by the user

**Comment by saswatsamal** [comment]
Nice suggestion. Will be fixing it v. soon :)
